kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name}}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name}}-sa # customize as required
  namespace: {{ .Release.Namespace}} # customize as required
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name}}-role
  apiGroup: rbac.authorization.k8s.io

# {{ .Chart.Name}}-role -->  {{ .Chart.Name}}-sa 
#  {{ .Chart.Name}}-sa --> deployment(pod)  