apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ .Chart.Name}}-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.App.gcp_sa}}@{{ .Values.App.gcp_projectID }}.iam.gserviceaccount.com
  labels:
    app: app2