apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngx-d
  labels:
    app: ng1
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          name: web
        envFrom:
        - secretRef:
            name: my-sec1  
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        volumeMounts:
        - name: user-info
          mountPath: /etc/certs
        - name: user-in2
          mountPath: /etc/dat1
      volumes:
      - name: user-info
        secret:
          secretName: my-sec3
      - name: user-in2
        secret:
          secretName: my-sec